language: objective-c  
osx_image: xcode7.1
xcode_project: RagicViewer.xcodeproj
xcode_scheme: RagicViewer
xcode_sdk: iphonesimulator9.0

before_install:
  - gem install cocoapods -v '0.39'
  - pod install
 
script:
  - xctool -workspace RagicViewer.xcworkspace -scheme RagicViewer -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
