language: objective-c 
 
before_install:
  - gem install cocoapods -v '0.34.4'
  - pod install
 
script:
  - xctool -workspace RagicViewer.xcworkspace -scheme RagicViewer -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
