language: objective-c  
osx_image: xcode7.1

before_install:
  - gem install cocoapods -v '0.39'
  - pod install
 
script:
  - xctool -workspace RagicViewer.xcworkspace -scheme RagicViewer -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
